--CREATE USER SYSTEM_MATERIAL IDENTIFIED BY "MATERIAL#123456";
--GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO SYSTEM_MATERIAL;
--ALTER USER SYSTEM_MATERIAL QUOTA UNLIMITED ON USERS;

CREATE TABLE PRODUCTS (
  ID           RAW(16)        NOT NULL,
  CODE         VARCHAR2(9),
  DESCRIPTION  VARCHAR2(90),
  TYPE_PRODUCT VARCHAR2(3),
  BARCODE      VARCHAR2(15),
  PRICE        NUMBER(10,2),

  CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID),
  CONSTRAINT UK_PRODUCTS_CODE UNIQUE (CODE),
  CONSTRAINT CK_PRODUCTS_TYPE_PRODUCT CHECK (TYPE_PRODUCT = 'FP')
);

CREATE TABLE RAW_MATERIAL (
  ID           RAW(16)        NOT NULL,
  CODE         VARCHAR2(9),
  DESCRIPTION  VARCHAR2(90),
  TYPE_PRODUCT VARCHAR2(3),
  BARCODE      VARCHAR2(15),
  COST         NUMBER(10,2),

  CONSTRAINT PK_RAW_MATERIAL PRIMARY KEY (ID),
  CONSTRAINT UK_RAW_MATERIAL_CODE UNIQUE (CODE),
  CONSTRAINT CK_RAW_MATERIAL_TYPE_PRODUCT CHECK (TYPE_PRODUCT = 'RAW')
);

CREATE TABLE PRODUCT_STRUCTURE (
  ID                   RAW(16)        NOT NULL,
  PRODUCT_CODE          VARCHAR2(9),
  DESCRIPTION_PRODUCT   VARCHAR2(90),
  RAW_CODE              VARCHAR2(9),
  DESCRIPTION_RAW       VARCHAR2(90),
  QUANTITY              FLOAT,
  LOSS                 FLOAT,

  CONSTRAINT PK_PRODUCT_STRUCTURE PRIMARY KEY (ID)
);

CREATE TABLE STOCK (
  ID                   RAW(16)        NOT NULL,
  CODE          VARCHAR2(9),
  DESCRIPTION   VARCHAR2(90),
  TYPE_PRODUCT VARCHAR2(3),
  STOCK_QUANTITY              FLOAT,
  BARCODE      VARCHAR2(15),

  CONSTRAINT PK_STOCK PRIMARY KEY (ID)
);



