INSERT INTO PRODUCT_STRUCTURE (
  ID, PRODUCT_CODE, DESCRIPTION_PRODUCT, RAW_CODE, DESCRIPTION_RAW, QUANTITY, LOSS
) VALUES (
  SYS_GUID(), 'PRD000001', 'Memória RAM DDR4 8GB', 'RAW000001', 'Chip de memória DDR4 1Gb', 8, 0.02
);

INSERT INTO PRODUCT_STRUCTURE (
  ID, PRODUCT_CODE, DESCRIPTION_PRODUCT, RAW_CODE, DESCRIPTION_RAW, QUANTITY, LOSS
) VALUES (
  SYS_GUID(), 'PRD000001', 'Memória RAM DDR4 8GB', 'RAW000002', 'PCB 8 camadas (módulo RAM)', 1, 0.01
);

/* PRD000002 (SSD 480GB) -> 2 MPs */
INSERT INTO PRODUCT_STRUCTURE (
  ID, PRODUCT_CODE, DESCRIPTION_PRODUCT, RAW_CODE, DESCRIPTION_RAW, QUANTITY, LOSS
) VALUES (
  SYS_GUID(), 'PRD000002', 'SSD SATA 480GB', 'RAW000003', 'Controladora SSD SATA', 1, 0.01
);

INSERT INTO PRODUCT_STRUCTURE (
  ID, PRODUCT_CODE, DESCRIPTION_PRODUCT, RAW_CODE, DESCRIPTION_RAW, QUANTITY, LOSS
) VALUES (
  SYS_GUID(), 'PRD000002', 'SSD SATA 480GB', 'RAW000004', 'NAND Flash 64Gb', 8, 0.03
);

/* PRD000003 (Fonte 500W) -> 2 MPs */
INSERT INTO PRODUCT_STRUCTURE (
  ID, PRODUCT_CODE, DESCRIPTION_PRODUCT, RAW_CODE, DESCRIPTION_RAW, QUANTITY, LOSS
) VALUES (
  SYS_GUID(), 'PRD000003', 'Fonte ATX 500W', 'RAW000005', 'Carcaça metálica (fonte ATX)', 1, 0.01
);

INSERT INTO PRODUCT_STRUCTURE (
  ID, PRODUCT_CODE, DESCRIPTION_PRODUCT, RAW_CODE, DESCRIPTION_RAW, QUANTITY, LOSS
) VALUES (
  SYS_GUID(), 'PRD000003', 'Fonte ATX 500W', 'RAW000006', 'Transformador 500W', 1, 0.02
);